/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.ufes.sofwareacessousuario.view;

/**
 *
 * @author heflainrmendes
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        btnUser = new javax.swing.JMenu();
        btnChangePassword = new javax.swing.JMenuItem();
        btnViewNotificaition = new javax.swing.JMenuItem();
        btnExit = new javax.swing.JMenuItem();
        btnAdmin = new javax.swing.JMenu();
        btnSendNotification = new javax.swing.JMenuItem();
        btnAddUser = new javax.swing.JMenuItem();
        btnAuthorizeUser = new javax.swing.JMenuItem();
        btnConfig = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Software para acesso de usuários ao sistema");
        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);

        menuBar.setPreferredSize(new java.awt.Dimension(91, 40));

        btnUser.setMnemonic('f');
        btnUser.setText("User");

        btnChangePassword.setMnemonic('o');
        btnChangePassword.setText("change password");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });
        btnUser.add(btnChangePassword);

        btnViewNotificaition.setMnemonic('s');
        btnViewNotificaition.setText("view notification");
        btnUser.add(btnViewNotificaition);

        btnExit.setMnemonic('x');
        btnExit.setText("exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        btnUser.add(btnExit);

        menuBar.add(btnUser);

        btnAdmin.setMnemonic('e');
        btnAdmin.setText("Admin");

        btnSendNotification.setMnemonic('t');
        btnSendNotification.setText("send notifications");
        btnSendNotification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendNotificationActionPerformed(evt);
            }
        });
        btnAdmin.add(btnSendNotification);

        btnAddUser.setMnemonic('y');
        btnAddUser.setText("add user");
        btnAdmin.add(btnAddUser);

        btnAuthorizeUser.setMnemonic('p');
        btnAuthorizeUser.setText("authorize user");
        btnAdmin.add(btnAuthorizeUser);

        btnConfig.setText("config");
        btnAdmin.add(btnConfig);

        menuBar.add(btnAdmin);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 922, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnSendNotificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendNotificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSendNotificationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAddUser;
    private javax.swing.JMenu btnAdmin;
    private javax.swing.JMenuItem btnAuthorizeUser;
    private javax.swing.JMenuItem btnChangePassword;
    private javax.swing.JMenuItem btnConfig;
    private javax.swing.JMenuItem btnExit;
    private javax.swing.JMenuItem btnSendNotification;
    private javax.swing.JMenu btnUser;
    private javax.swing.JMenuItem btnViewNotificaition;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
