/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.ufes.sofwareacessousuario.view;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author heflainrmendes
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        lblUserName = new javax.swing.JLabel();
        btnAmountNotifications = new javax.swing.JButton();
        lblUserType = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        btnUser = new javax.swing.JMenu();
        btnChangePassword = new javax.swing.JMenuItem();
        btnViewNotificaition = new javax.swing.JMenuItem();
        btnExit = new javax.swing.JMenuItem();
        btnAdmin = new javax.swing.JMenu();
        btnSendNotification = new javax.swing.JMenuItem();
        btnAddUser = new javax.swing.JMenuItem();
        btnAuthorizeUser = new javax.swing.JMenuItem();
        btnConfig = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Software para acesso de usuários ao sistema");
        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 898, Short.MAX_VALUE)
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblUserName.setBackground(new java.awt.Color(255, 255, 255));
        lblUserName.setForeground(new java.awt.Color(0, 0, 0));
        lblUserName.setText("jLabel1");

        btnAmountNotifications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmountNotificationsActionPerformed(evt);
            }
        });

        lblUserType.setForeground(new java.awt.Color(0, 0, 0));
        lblUserType.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(255, 255, 255)
                .addComponent(lblUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAmountNotifications, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUserType, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btnAmountNotifications, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUserName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        menuBar.setPreferredSize(new java.awt.Dimension(91, 40));

        btnUser.setMnemonic('f');
        btnUser.setText("User");

        btnChangePassword.setMnemonic('o');
        btnChangePassword.setText("change password");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });
        btnUser.add(btnChangePassword);

        btnViewNotificaition.setMnemonic('s');
        btnViewNotificaition.setText("view notification");
        btnUser.add(btnViewNotificaition);

        btnExit.setMnemonic('x');
        btnExit.setText("exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        btnUser.add(btnExit);

        menuBar.add(btnUser);

        btnAdmin.setMnemonic('e');
        btnAdmin.setText("Admin");

        btnSendNotification.setMnemonic('t');
        btnSendNotification.setText("send notifications");
        btnSendNotification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendNotificationActionPerformed(evt);
            }
        });
        btnAdmin.add(btnSendNotification);

        btnAddUser.setMnemonic('y');
        btnAddUser.setText("add user");
        btnAdmin.add(btnAddUser);

        btnAuthorizeUser.setMnemonic('p');
        btnAuthorizeUser.setText("authorize user");
        btnAuthorizeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthorizeUserActionPerformed(evt);
            }
        });
        btnAdmin.add(btnAuthorizeUser);

        btnConfig.setText("config");
        btnAdmin.add(btnConfig);

        menuBar.add(btnAdmin);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnSendNotificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendNotificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSendNotificationActionPerformed

    private void btnAmountNotificationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmountNotificationsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAmountNotificationsActionPerformed

    private void btnAuthorizeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthorizeUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAuthorizeUserActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PrincipalView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAddUser;
    private javax.swing.JMenu btnAdmin;
    private javax.swing.JButton btnAmountNotifications;
    private javax.swing.JMenuItem btnAuthorizeUser;
    private javax.swing.JMenuItem btnChangePassword;
    private javax.swing.JMenuItem btnConfig;
    private javax.swing.JMenuItem btnExit;
    private javax.swing.JMenuItem btnSendNotification;
    private javax.swing.JMenu btnUser;
    private javax.swing.JMenuItem btnViewNotificaition;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserType;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JDesktopPane pnlPrincipal;
    // End of variables declaration//GEN-END:variables

    public JMenuItem getBtnAddUser() {
        return btnAddUser;
    }

    public JMenu getBtnAdmin() {
        return btnAdmin;
    }

    public JButton getBtnAmountNotifications() {
        return btnAmountNotifications;
    }

    public JMenuItem getBtnAuthorizeUser() {
        return btnAuthorizeUser;
    }

    public JMenuItem getBtnChangePassword() {
        return btnChangePassword;
    }

    public JMenuItem getBtnConfig() {
        return btnConfig;
    }

    public JMenuItem getBtnExit() {
        return btnExit;
    }

    public JMenuItem getBtnSendNotification() {
        return btnSendNotification;
    }

    public JMenu getBtnUser() {
        return btnUser;
    }

    public JMenuItem getBtnViewNotificaition() {
        return btnViewNotificaition;
    }

    public JLabel getLblUserName() {
        return lblUserName;
    }

    public JLabel getLblUserType() {
        return lblUserType;
    }

    public JDesktopPane getPnlPrincipal() {
        return pnlPrincipal;
    }
}
